version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=flightreservation
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 5
  flighreservation-app:
    image: openjdk:11
    build: 
      context: .   
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flightreservation
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=